"""Initial schema with org_id for multi-tenancy

Revision ID: 1163929d2cb6
Revises: 
Create Date: 2026-05-01 17:55:13.794963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1163929d2cb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='orgplan'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.add_column('courses', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.drop_index('ix_courses_code', table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_foreign_key(None, 'courses', 'organizations', ['org_id'], ['id'])
    op.add_column('departments', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'departments', 'organizations', ['org_id'], ['id'])
    op.add_column('users', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'org_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'org_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index('ix_courses_code', 'courses', ['code'], unique=1)
    op.drop_column('courses', 'org_id')
    op.drop_table('organizations')
    # ### end Alembic commands ###
